### ISSUE TITLE
PHP version (7.3.5)

### ISSUE THREAD

**Issue by posidonius** [iMi-digital/magento2-store-switch-all-store-views#2]
Using composer to attempt an install, I get this error:

`Package imi/magento2-store-switch-all-store-views at version  has a PHP requirement incompatible with your PHP version (7.3.5)`

I see in composer.json you have, `"php": "~7.2.0"` ... is this extension really not compatible with PHP 7.3.5?

**Comment by imino123** [comment]
This module should work with <code>PHP 7.3</code>.  I've tested it using <code>PHP 7.3.21</code> using <code>Magento 2.3.5p1</code>  

You will need to manually install the module, as it won't install using <code>composer</code> on <code>PHP 7.3</code>

To do this, create the following directory structure from your Magento root:

<code><your_magento_root>/app/code/IMI/</code>

Download or upload the latest <b>magento2-store-switch-all-store-views</b> <code>.zip</code> file to this newly created directory:

downlod or upload to -> <code><your_magento_root>/app/code/IMI/</code>

You will then need to unzip the file:

<code>unzip <your_magento_root>/app/code/IMI/magento2-store-switch-all-store-views-0.1.1.zip</code>

A folder named "<b>magento2-store-switch-all-store-views-0.1.1</b>" will be extracted.  This folder will need to be renamed.

Rename this extracted directory to "StoreSwitch".  You can do this using an FTP software, <code>ssh</code> or a file manager.

Here I use a bash command in <code>ssh</code> to rename the directory to "StoreSwitch":

<code>mv     <your_magento_root>/app/code/IMI/magento2-store-switch-all-store-views-0.1.1    StoreSwitch</code>

Then run these commands from your Magento root to install the module:

<code>php bin/magento setup:upgrade</code>
<code>php bin/magento setup:di:compile</code>
<code>php bin/magento cache:flush</code>

Finally, enable StoreSwitch from your Magento admin dashboard:

<b>Stores > Settings > Configurations > IMI > Store Switch > Enable Switch</b>

**Comment by amenk** [comment]
We should drop the PHP Version requirement in favor of Magento version constraints..

**Comment by amenk** [comment]
dropped version constraint
