### ISSUE TITLE
Module does not handle multiple domains

### ISSUE THREAD

**Issue by posidonius** [iMi-digital/magento2-store-switch-all-store-views#3]
This module does not properly switch between websites when they are on different domains.

The switcher shows all store views but when one of the store views is on another domain, it doesn't seem to switch.

**Comment by amenk** [comment]
Thanks for your report.
I believe we use the module in a multi domain setup and it works.

What is your setup exactly to reproduce the problem?

Which URL is shown when hovering over a different language in the switcher?

Which Magento version are you using?

**Comment by amenk** [comment]
@posidonius is this still an issue? Do you have details?

**Comment by posidonius** [comment]
@amenk When I initially opened this ticket, I was testing your extension in development using Magento 2.3.5. I decided to remove it before going to production. I never got it to work as expected. It showed all stores on the same domain.

**Comment by amenk** [comment]
Sorry to hear that, but thanks for letting us know..I believe we have it working with multiple domains but another Magento version.
